version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - revive
    - govet
    - staticcheck
    - gocritic
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
        - (io.Reader).Close
        - (*database/sql.DB).Close
        - (*github.com/bwmarrin/discordgo.Session).Close
        - (github.com/jackc/pgx/v5.Tx).Rollback
    gocritic:
      disabled-checks:
        - exitAfterDefer 
    revive:
      rules:
        - name: unused-parameter
          exclude: ["**/*_test.go"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0