version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - revive
    - govet
    - staticcheck
    - gocritic
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
        - (io.Reader).Close
        - (*database/sql.DB).Close

issues:
  max-issues-per-linter: 0
  max-same-issues: 0