BEGIN;
CREATE SCHEMA IF NOT EXISTS public;
CREATE SEQUENCE ball_ids START 1 INCREMENT 1;
CREATE TABLE IF NOT EXISTS balls (
    id BIGINT PRIMARY KEY DEFAULT nextval('ball_ids'),
    brand STRING NOT NULL,
    name STRING NOT NULL,
    image_url STRING NOT NULL,
    approved_at TIMESTAMPTZ NOT NULL
);
COMMIT;
